//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pal5Mod_BeautifyRepair.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pal5Mod_BeautifyRepair.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 This MOD is designed to enhance the gaming experience, providing a better experience for players who wish to revisit the game. We hope it can be of help to you 的本地化字符串。
        /// </summary>
        public static string AboutWindow_description {
            get {
                return ResourceManager.GetString("AboutWindow_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 build: .Net WPF 的本地化字符串。
        /// </summary>
        public static string AboutWindow_Programlanguage {
            get {
                return ResourceManager.GetString("AboutWindow_Programlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project: 的本地化字符串。
        /// </summary>
        public static string AboutWindow_SourceCode {
            get {
                return ResourceManager.GetString("AboutWindow_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pal5 BeautifyRepair Mod 的本地化字符串。
        /// </summary>
        public static string AboutWindow_TextBlockTitle {
            get {
                return ResourceManager.GetString("AboutWindow_TextBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Pal5 Beautify Repair Mod 的本地化字符串。
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Borrowed Items MOD Patch/Tool: 的本地化字符串。
        /// </summary>
        public static string BorrowToolsText {
            get {
                return ResourceManager.GetString("BorrowToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Default 的本地化字符串。
        /// </summary>
        public static string Button_RestoreDefault {
            get {
                return ResourceManager.GetString("Button_RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Font 的本地化字符串。
        /// </summary>
        public static string CustomFont {
            get {
                return ResourceManager.GetString("CustomFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select your preferred font from the list on the left 的本地化字符串。
        /// </summary>
        public static string Customfontlist_description {
            get {
                return ResourceManager.GetString("Customfontlist_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Font List 的本地化字符串。
        /// </summary>
        public static string Customfontlist_WindowTitle {
            get {
                return ResourceManager.GetString("Customfontlist_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chillkai (Recommended) 的本地化字符串。
        /// </summary>
        public static string Font_Chillkai {
            get {
                return ResourceManager.GetString("Font_Chillkai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Huakang Tangfeng Li (Default) 的本地化字符串。
        /// </summary>
        public static string Font_Default {
            get {
                return ResourceManager.GetString("Font_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xiawu 的本地化字符串。
        /// </summary>
        public static string Font_Xiawu {
            get {
                return ResourceManager.GetString("Font_Xiawu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some fonts are not supported. It is recommended to select .ttf font files. If text does not display or displays incompletely in the game, please try another font. 的本地化字符串。
        /// </summary>
        public static string Fontdescription {
            get {
                return ResourceManager.GetString("Fontdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional Notes 的本地化字符串。
        /// </summary>
        public static string FontTips {
            get {
                return ResourceManager.GetString("FontTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path does not exist. Please re-enter or select 的本地化字符串。
        /// </summary>
        public static string GeneralFocus_Pathnotexist {
            get {
                return ResourceManager.GetString("GeneralFocus_Pathnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game directory not recognized. Please reselect 的本地化字符串。
        /// </summary>
        public static string GeneralPathText_NoPath {
            get {
                return ResourceManager.GetString("GeneralPathText_NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game directory recognized 的本地化字符串。
        /// </summary>
        public static string GeneralPathText_PathOK {
            get {
                return ResourceManager.GetString("GeneralPathText_PathOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommended Fonts 的本地化字符串。
        /// </summary>
        public static string Group_RecommendedFonts {
            get {
                return ResourceManager.GetString("Group_RecommendedFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used to hide the battle UI interface for ease of recording.
        ///The battle victory interface is hidden,
        ///Hide status names and damage numbers. 的本地化字符串。
        /// </summary>
        public static string HideBattleUI_description {
            get {
                return ResourceManager.GetString("HideBattleUI_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Battle UI 的本地化字符串。
        /// </summary>
        public static string HideBattleUI_Header {
            get {
                return ResourceManager.GetString("HideBattleUI_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: The game may crash when running. Try restarting the game. 的本地化字符串。
        /// </summary>
        public static string HideBattleUI_NoteTip {
            get {
                return ResourceManager.GetString("HideBattleUI_NoteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Battle UI Interface 的本地化字符串。
        /// </summary>
        public static string HideBattleUI_Title {
            get {
                return ResourceManager.GetString("HideBattleUI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select game path 的本地化字符串。
        /// </summary>
        public static string Hint_SelectGamePath {
            get {
                return ResourceManager.GetString("Hint_SelectGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paladin Five 的本地化字符串。
        /// </summary>
        public static string Label_Pal5 {
            get {
                return ResourceManager.GetString("Label_Pal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paladin Five Prequel 的本地化字符串。
        /// </summary>
        public static string Label_Pal5Q {
            get {
                return ResourceManager.GetString("Label_Pal5Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Lang_EN {
            get {
                return ResourceManager.GetString("Lang_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        public static string Lang_SC {
            get {
                return ResourceManager.GetString("Lang_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SC 的本地化字符串。
        /// </summary>
        public static string Lang_Simplified {
            get {
                return ResourceManager.GetString("Lang_Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese 的本地化字符串。
        /// </summary>
        public static string Lang_TC {
            get {
                return ResourceManager.GetString("Lang_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TC 的本地化字符串。
        /// </summary>
        public static string Lang_Traditional {
            get {
                return ResourceManager.GetString("Lang_Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link 的本地化字符串。
        /// </summary>
        public static string Link_Text {
            get {
                return ResourceManager.GetString("Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help Manual 的本地化字符串。
        /// </summary>
        public static string Menu_Helpdoc {
            get {
                return ResourceManager.GetString("Menu_Helpdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        public static string Menu_ProjectRepo {
            get {
                return ResourceManager.GetString("Menu_ProjectRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Proportion Adjustment and Skin Whitening 的本地化字符串。
        /// </summary>
        public static string Msg_Adjustment_Title {
            get {
                return ResourceManager.GetString("Msg_Adjustment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font changed successfully!
        ///
        ///If the game is running, please close the game and restart it to see the effect.
        ///If it doesn&apos;t take effect, please restart the game or change the font. 的本地化字符串。
        /// </summary>
        public static string Msg_FontEditSuccess {
            get {
                return ResourceManager.GetString("Msg_FontEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Modification 的本地化字符串。
        /// </summary>
        public static string Msg_FontEditTitle {
            get {
                return ResourceManager.GetString("Msg_FontEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Battle UI Interface 的本地化字符串。
        /// </summary>
        public static string Msg_HideBattleUI_Title {
            get {
                return ResourceManager.GetString("Msg_HideBattleUI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pal5Mod_BeautifyRepair folder not found. Please place it in the same directory as the program. 的本地化字符串。
        /// </summary>
        public static string Msg_NoMODfolder {
            get {
                return ResourceManager.GetString("Msg_NoMODfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pal5.exe not found in the selected directory. Please confirm if it&apos;s the correct game directory. 的本地化字符串。
        /// </summary>
        public static string Msg_NoPal5exePath_error {
            get {
                return ResourceManager.GetString("Msg_NoPal5exePath_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t selected a game path yet! Please select a path from the first option in the left menu~ 的本地化字符串。
        /// </summary>
        public static string Msg_NoPathSelected {
            get {
                return ResourceManager.GetString("Msg_NoPathSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t selected a font size yet! Please select one and click Apply! 的本地化字符串。
        /// </summary>
        public static string Msg_NoSelectAllFontSize {
            get {
                return ResourceManager.GetString("Msg_NoSelectAllFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t selected Pal5/Pal5 Prequel game path yet! Please select a path from the first option in the left menu~ 的本地化字符串。
        /// </summary>
        public static string Msg_NoSelectAllPath {
            get {
                return ResourceManager.GetString("Msg_NoSelectAllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t selected a resolution yet! Please select one and click Apply 的本地化字符串。
        /// </summary>
        public static string Msg_NoSelectedAllresolution {
            get {
                return ResourceManager.GetString("Msg_NoSelectedAllresolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t selected a language yet! Please select one and click Apply! 的本地化字符串。
        /// </summary>
        public static string Msg_NoSelectedLang {
            get {
                return ResourceManager.GetString("Msg_NoSelectedLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t selected a font yet! Please select one and click Apply! 的本地化字符串。
        /// </summary>
        public static string Msg_NOselectFont {
            get {
                return ResourceManager.GetString("Msg_NOselectFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust Message Dialog Font Size 的本地化字符串。
        /// </summary>
        public static string Msg_PopoSize_Title {
            get {
                return ResourceManager.GetString("Msg_PopoSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font size adjusted successfully!
        ///
        ///If the game is running, please close the game and restart it to see the effect.
        ///If it doesn&apos;t take effect, please restart the game or try applying again. 的本地化字符串。
        /// </summary>
        public static string Msg_PopoSizeSuccess {
            get {
                return ResourceManager.GetString("Msg_PopoSizeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program exception occurred 的本地化字符串。
        /// </summary>
        public static string Msg_Programexception {
            get {
                return ResourceManager.GetString("Msg_Programexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Initial Default Settings 的本地化字符串。
        /// </summary>
        public static string Msg_Restoredefaultsettings {
            get {
                return ResourceManager.GetString("Msg_Restoredefaultsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All settings have been restored to default!
        ///
        ///If the game is running, please close the game and restart it to see the effect. 的本地化字符串。
        /// </summary>
        public static string Msg_Restoredefaultsettings_describe {
            get {
                return ResourceManager.GetString("Msg_Restoredefaultsettings_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select font file 的本地化字符串。
        /// </summary>
        public static string Msg_SelectedFontFile_Title {
            get {
                return ResourceManager.GetString("Msg_SelectedFontFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applied successfully!
        ///
        ///If the game is running, please close the game and restart it to see the effect. 的本地化字符串。
        /// </summary>
        public static string Msg_TrueSuccess {
            get {
                return ResourceManager.GetString("Msg_TrueSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution extension adjusted successfully!
        ///
        ///If the game is running, please close the game and restart it to see the effect.
        ///If it doesn&apos;t take effect or crashes occur, please restart the game or try applying again. 的本地化字符串。
        /// </summary>
        public static string Msg_UIresolution_Success {
            get {
                return ResourceManager.GetString("Msg_UIresolution_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Interface Resolution Extension 的本地化字符串。
        /// </summary>
        public static string Msg_UIresolution_Title {
            get {
                return ResourceManager.GetString("Msg_UIresolution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only for modifying the body proportions of the four protagonists in the DLC &apos;Dream Hua Huan Dou&apos;. 的本地化字符串。
        /// </summary>
        public static string Note_Pal5Q_DLC {
            get {
                return ResourceManager.GetString("Note_Pal5Q_DLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select from External File 的本地化字符串。
        /// </summary>
        public static string outsideFont {
            get {
                return ResourceManager.GetString("outsideFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select Pal5 root directory 的本地化字符串。
        /// </summary>
        public static string Pal5_SelectGamePath {
            get {
                return ResourceManager.GetString("Pal5_SelectGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select Pal5 Prequel root directory 的本地化字符串。
        /// </summary>
        public static string Pal5Q_SelectGamePath {
            get {
                return ResourceManager.GetString("Pal5Q_SelectGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Game Root Directory 的本地化字符串。
        /// </summary>
        public static string Placeholder_SelectRoot {
            get {
                return ResourceManager.GetString("Placeholder_SelectRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select option and click &quot;Apply&quot; button 的本地化字符串。
        /// </summary>
        public static string Prompt_PleaseSelectThenApply {
            get {
                return ResourceManager.GetString("Prompt_PleaseSelectThenApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the game path first, then select the function 的本地化字符串。
        /// </summary>
        public static string Prompt_SelectGameThenFunction {
            get {
                return ResourceManager.GetString("Prompt_SelectGameThenFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore all game configurations to initial settings.
        ///If previous feature applications failed, you can try restoring initial settings. 的本地化字符串。
        /// </summary>
        public static string RestoreDefault_description {
            get {
                return ResourceManager.GetString("RestoreDefault_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Settings 的本地化字符串。
        /// </summary>
        public static string RestoreDefault_Header {
            get {
                return ResourceManager.GetString("RestoreDefault_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Initial Settings 的本地化字符串。
        /// </summary>
        public static string RestoreDefault_Title {
            get {
                return ResourceManager.GetString("RestoreDefault_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Large (48) 的本地化字符串。
        /// </summary>
        public static string Size_ExtraLarge {
            get {
                return ResourceManager.GetString("Size_ExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large (38) 的本地化字符串。
        /// </summary>
        public static string Size_Large {
            get {
                return ResourceManager.GetString("Size_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium (28) 的本地化字符串。
        /// </summary>
        public static string Size_Medium {
            get {
                return ResourceManager.GetString("Size_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small (Default, 18) 的本地化字符串。
        /// </summary>
        public static string Size_Small {
            get {
                return ResourceManager.GetString("Size_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select from Installed System Fonts 的本地化字符串。
        /// </summary>
        public static string SystemInstallFont {
            get {
                return ResourceManager.GetString("SystemInstallFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature adjusts the body proportions of the four main characters&apos; models and lightens their skin tone.
        ///Paladin Five Prequel DLC &quot;Menghua Huandou&quot; also features four main characters, which can also be selected from the list below 的本地化字符串。
        /// </summary>
        public static string Tab_Adjustment_Description {
            get {
                return ResourceManager.GetString("Tab_Adjustment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Adjustment
        ///and Skin Whitening 的本地化字符串。
        /// </summary>
        public static string Tab_Adjustment_Header {
            get {
                return ResourceManager.GetString("Tab_Adjustment_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Adjustment / Skin Whitening 的本地化字符串。
        /// </summary>
        public static string Tab_Adjustment_Title {
            get {
                return ResourceManager.GetString("Tab_Adjustment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature changes the game font to a more comfortable one.
        ///Please select your preferred font 的本地化字符串。
        /// </summary>
        public static string Tab_FontEdit_Description {
            get {
                return ResourceManager.GetString("Tab_FontEdit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Modification 的本地化字符串。
        /// </summary>
        public static string Tab_FontEdit_Header {
            get {
                return ResourceManager.GetString("Tab_FontEdit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Modification 的本地化字符串。
        /// </summary>
        public static string Tab_FontEdit_Title {
            get {
                return ResourceManager.GetString("Tab_FontEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used to adjust the font size of message bubble dialog boxes, NPC dialog boxes and selection boxes, story message boxes, save/load game prompt boxes, return interface prompt boxes, exit game prompt boxes, etc. 的本地化字符串。
        /// </summary>
        public static string Tab_Poposize_Description {
            get {
                return ResourceManager.GetString("Tab_Poposize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MessageDialog Size 的本地化字符串。
        /// </summary>
        public static string Tab_Poposize_Header {
            get {
                return ResourceManager.GetString("Tab_Poposize_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: This feature conflicts with the UI interface extension feature. The UI interface feature will be applied first before adjusting the message dialog font size. 的本地化字符串。
        /// </summary>
        public static string Tab_Poposize_Note {
            get {
                return ResourceManager.GetString("Tab_Poposize_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust Message Dialog Font Size 的本地化字符串。
        /// </summary>
        public static string Tab_Poposize_Title {
            get {
                return ResourceManager.GetString("Tab_Poposize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Game Path 的本地化字符串。
        /// </summary>
        public static string Tab_SelectGamePath {
            get {
                return ResourceManager.GetString("Tab_SelectGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks for the contributions made by these people! 的本地化字符串。
        /// </summary>
        public static string TabAbout_borrowText {
            get {
                return ResourceManager.GetString("TabAbout_borrowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program is a beta version and still has many issues. If you encounter any problems, please provide feedback to me on Github or Gitee 的本地化字符串。
        /// </summary>
        public static string TabAbout_description {
            get {
                return ResourceManager.GetString("TabAbout_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About/Feedback 的本地化字符串。
        /// </summary>
        public static string TabAbout_Header {
            get {
                return ResourceManager.GetString("TabAbout_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AI assistant: ChatGPT
        ///Test: 清风涧碎花弄影、水月澄明 的本地化字符串。
        /// </summary>
        public static string TabAbout_tester {
            get {
                return ResourceManager.GetString("TabAbout_tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About/Feedback 的本地化字符串。
        /// </summary>
        public static string TabAbout_Title {
            get {
                return ResourceManager.GetString("TabAbout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extend the UI interface to 1080P and 2K high resolution. If you don&apos;t like it, you can click to restore the default settings. 的本地化字符串。
        /// </summary>
        public static string UIresolution_description {
            get {
                return ResourceManager.GetString("UIresolution_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fullscreen 的本地化字符串。
        /// </summary>
        public static string UIresolution_FullScreen {
            get {
                return ResourceManager.GetString("UIresolution_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UIResolution
        ///Extension 的本地化字符串。
        /// </summary>
        public static string UIresolution_Header {
            get {
                return ResourceManager.GetString("UIresolution_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After selecting a resolution, the game interface will remain as the new interface without needing to reapply. To switch to another resolution, you need to reselect and adjust, otherwise there will be conflicts and display misalignment.
        ///3840x2160 (4K) resolution does not display all text completely. The recommended solution is to select 1920x1080 resolution with fullscreen mode, or adjust the program&apos;s high DPI settings yourself. 的本地化字符串。
        /// </summary>
        public static string UIresolution_Note {
            get {
                return ResourceManager.GetString("UIresolution_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Important Notes 的本地化字符串。
        /// </summary>
        public static string UIresolution_NoteHeader {
            get {
                return ResourceManager.GetString("UIresolution_NoteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select resolution 的本地化字符串。
        /// </summary>
        public static string UIresolution_Selectresolution {
            get {
                return ResourceManager.GetString("UIresolution_Selectresolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string UIresolution_SettingsButton {
            get {
                return ResourceManager.GetString("UIresolution_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you need to adjust game settings, please click: 的本地化字符串。
        /// </summary>
        public static string UIresolution_Settingsdescription {
            get {
                return ResourceManager.GetString("UIresolution_Settingsdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Interface Resolution Extension 的本地化字符串。
        /// </summary>
        public static string UIresolution_Title {
            get {
                return ResourceManager.GetString("UIresolution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pal5 BeautifyRepair Mod 的本地化字符串。
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
